name: jnv_mobile
description: JNV parent mobile app
publish_to: "none"
version: 0.1.4+5

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_messaging: ^16.1.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/jnv-logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/jnv-logo.png
  adaptive_icon_background: "#0B1F3B"
  adaptive_icon_foreground: assets/jnv-logo.png
